# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiteaConfigWave < Formula
  desc "CLI tool to manage Gitea repository settings at scale"
  homepage "https://github.com/DUALSTACKS/gitea-config-wave"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.1.0/gitea-config-wave_0.1.0_darwin_amd64.tar.gz"
      sha256 "aaed9aa46261a1716bc3d9e8695c4021b170e960d9d77c9c664a085bf2e6c560"

      def install
        bin.install "gitea-config-wave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.1.0/gitea-config-wave_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba0e7ae0bb12a7a11574fedc066bb35e113d174a018015f6f89655796fbfb776"

      def install
        bin.install "gitea-config-wave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.1.0/gitea-config-wave_0.1.0_linux_amd64.tar.gz"
        sha256 "f616f9192ac79790979fb1b8ca79197ff233e3bf4a360e4e120dff3d7db9ae5a"

        def install
          bin.install "gitea-config-wave"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.1.0/gitea-config-wave_0.1.0_linux_arm64.tar.gz"
        sha256 "4171a1e02953fdc2638b7492d7090b6c67027e52e40a2b38d97e9acd000f692b"

        def install
          bin.install "gitea-config-wave"
        end
      end
    end
  end

  test do
    system "#{bin}/gitea-config-wave --version"
  end
end
