# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiteaConfigWave < Formula
  desc "CLI tool to manage Gitea repository settings at scale"
  homepage "https://github.com/DUALSTACKS/gitea-config-wave"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.3.0/gitea-config-wave_0.3.0_darwin_amd64.tar.gz"
      sha256 "e4edc454601d9f842577f47f276468e6550767f791ed310134ace9568f99f57a"

      def install
        bin.install "gitea-config-wave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.3.0/gitea-config-wave_0.3.0_darwin_arm64.tar.gz"
      sha256 "6b4ed86ad897ce364d1c376dddc5d8b8eedcb79fa9efda83c3303c2dc8d057e8"

      def install
        bin.install "gitea-config-wave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.3.0/gitea-config-wave_0.3.0_linux_amd64.tar.gz"
        sha256 "f29cdbea4422300cba546a2cfc0a220ad6996717b9173d797ce94b4c93e79a5d"

        def install
          bin.install "gitea-config-wave"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DUALSTACKS/gitea-config-wave/releases/download/v0.3.0/gitea-config-wave_0.3.0_linux_arm64.tar.gz"
        sha256 "3a2d8fbf2798fd34ed985f7f23152cd50abc9bf8911fbe4bead6b793543023e3"

        def install
          bin.install "gitea-config-wave"
        end
      end
    end
  end

  test do
    system "#{bin}/gitea-config-wave --version"
  end
end
